/**:
  ros__parameters:

    # Planning group and link names
    Approach_Retrive: [0.04, 0.10]

    # Collision object for picking
    # CYLINDER object specifications
    object_dimensions: [0.08, 0.035] # [height, radius]
    object_pose: [0.083, 0.414, 0.05, 0.0, 0.0, 0.0]

    # Hole
    # intial_pose: [-0.313, 0.112646, -0.520424]
    intial_pose: [-0.495488, -0.0715697, -0.521245]

    perception_pose: [-0.381259, -0.0713642, -0.521245]

    # Arm z pose
    z_approach: 0.595
    # # Gripper grasp frame transform [x,y,z,r,p,y]
    # grasp_frame_transform: [0.0, 0.0, 0.1, 1.571, 0.785, 1.571]

    # # Place pose [x,y,z,r,p,y]
    # place_pose: [0.6, -0.15, 0.0, 0.0, 0.0, 0.0]
    # place_surface_offset: 0.0001 # place offset from table

    # # Valid distance range when approaching an object for picking
    # approach_object_min_dist: 0.1
    # approach_object_max_dist: 0.15

    # # Valid height range when lifting an object after pick
    # lift_object_min_dist: 0.01
    # lift_object_max_dist: 0.1